import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal Disclaimer | Revuzza",
  description:
    "Legal Disclaimer for Revuzza - terms governing use of revuzza.com and related services.",
};

export default function LegalPage() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold mb-4">Legal Disclaimer</h1>

      <p className="text-sm text-gray-500 mb-8">
        Last Updated: June 2026
      </p>

      <div className="space-y-6 text-gray-800 leading-relaxed">
        <p>
          Revuzza ("Revuzza," "we," "our," or "us") operates revuzza.com and related
          services (collectively, the "Platform") as a public review and
          information-sharing platform. This Disclaimer governs your use of the
          Platform and should be read together with our Terms and Conditions and
          Privacy Policy. By accessing or using the Platform, you acknowledge and
          agree to this Disclaimer.
        </p>

        <Section title="1. General Information Only">
          The content on the Platform is for general informational purposes only.
          It does not constitute professional, legal, financial, medical, or other
          advice. Users must independently evaluate information before making
          decisions.
        </Section>

        <Section title="2. User-Generated Content Disclaimer">
          Most content is generated by users. Revuzza does not verify, endorse, or
          guarantee the accuracy of user-generated content. Views expressed are
          solely those of the users.
        </Section>

        <Section title="3. No Guarantee of Accuracy">
          We do not guarantee accuracy, completeness, reliability, or timeliness of
          any content on the Platform. Information may change without notice.
        </Section>

        <Section title="4. Business Information Disclaimer">
          Business details may come from users or third parties. We do not guarantee
          that such information is accurate or up to date.
        </Section>

        <Section title="5. Reviews and Ratings Disclaimer">
          Reviews and ratings reflect individual opinions and experiences, which may
          vary widely. They should not be considered universal truth.
        </Section>

        <Section title="6. No Professional Relationship">
          Use of the Platform does not create any professional, advisory, or legal
          relationship between users and Revuzza.
        </Section>

        <Section title="7. Third-Party Links">
          The Platform may include links to third-party websites. We are not
          responsible for their content or practices.
        </Section>

        <Section title="8. Platform Availability">
          We do not guarantee uninterrupted access. The Platform may be modified or
          discontinued at any time.
        </Section>

        <Section title="9. No Warranties">
          The Platform is provided “as is” without warranties of any kind, including
          accuracy, reliability, or fitness for purpose.
        </Section>

        <Section title="10. Limitation of Responsibility">
          Revuzza is not liable for any loss or damage arising from use of the
          Platform or reliance on its content.
        </Section>

        <Section title="11. Changes to This Disclaimer">
          We may update this Disclaimer at any time. Continued use of the Platform
          means acceptance of changes.
        </Section>

    <Section title="12. Contact Information">
  Support: support@revuzza.com | Website: revuzza.com
</Section>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold">{title}</h2>
      <div className="text-gray-700 leading-relaxed">
        {children}
      </div>
    </section>
  );
}